set(TARGET_CPU "-mcpu=cortex-m0")
set(GCC_TOOLSET_ROOT "D:/STM32CubeIDE_1.15.0/STM32CubeIDE/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.12.3.rel1.win32_1.0.100.202403111256/tools/bin")
set(CMAKE_C_COMPILER_WORKS TRUE CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_WORKS TRUE CACHE INTERNAL "")
set(CMAKE_C_COMPILER_FORCED TRUE CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_FORCED TRUE CACHE INTERNAL "")
set(CMAKE_C_COMPILER_ID_RUN TRUE CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER_ID_RUN TRUE CACHE INTERNAL "")

set(CMAKE_C_COMPILER "${GCC_TOOLSET_ROOT}/arm-none-eabi-gcc.exe")
set(CMAKE_CXX_COMPILER "${GCC_TOOLSET_ROOT}/arm-none-eabi-g++.exe")
set(CMAKE_ASM_COMPILER "${GCC_TOOLSET_ROOT}/arm-none-eabi-gcc.exe")
set(CMAKE_AR "${GCC_TOOLSET_ROOT}/arm-none-eabi-ar.exe")
set(CMAKE_LINKER "${GCC_TOOLSET_ROOT}/arm-none-eabi-ld.exe")
set(CMAKE_OBJCOPY "${GCC_TOOLSET_ROOT}/arm-none-eabi-objcopy.exe")
set(CMAKE_SIZE "${GCC_TOOLSET_ROOT}/arm-none-eabi-size.exe")